/*
Copyright 2026 Rebellions Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package runtime

import (
	"sync"
)

// Ensure, that ConfiguratorMock does implement Configurator.
// If this is not the case, regenerate this file with moq.
var _ Configurator = &ConfiguratorMock{}

// ConfiguratorMock is a mock implementation of Configurator.
//
//	func TestSomethingThatUsesConfigurator(t *testing.T) {
//
//		// make and configure a mocked Configurator
//		mockedConfigurator := &ConfiguratorMock{
//			ConfigureFunc: func() error {
//				panic("mock out the Configure method")
//			},
//			DryRunFunc: func() (string, error) {
//				panic("mock out the DryRun method")
//			},
//		}
//
//		// use mockedConfigurator in code that requires Configurator
//		// and then make assertions.
//
//	}
type ConfiguratorMock struct {
	// ConfigureFunc mocks the Configure method.
	ConfigureFunc func() error

	// DryRunFunc mocks the DryRun method.
	DryRunFunc func() (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Configure holds details about calls to the Configure method.
		Configure []struct {
		}
		// DryRun holds details about calls to the DryRun method.
		DryRun []struct {
		}
	}
	lockConfigure sync.RWMutex
	lockDryRun    sync.RWMutex
}

// Configure calls ConfigureFunc.
func (mock *ConfiguratorMock) Configure() error {
	callInfo := struct {
	}{}
	mock.lockConfigure.Lock()
	mock.calls.Configure = append(mock.calls.Configure, callInfo)
	mock.lockConfigure.Unlock()
	if mock.ConfigureFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ConfigureFunc()
}

// ConfigureCalls gets all the calls that were made to Configure.
// Check the length with:
//
//	len(mockedConfigurator.ConfigureCalls())
func (mock *ConfiguratorMock) ConfigureCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockConfigure.RLock()
	calls = mock.calls.Configure
	mock.lockConfigure.RUnlock()
	return calls
}

// DryRun calls DryRunFunc.
func (mock *ConfiguratorMock) DryRun() (string, error) {
	callInfo := struct {
	}{}
	mock.lockDryRun.Lock()
	mock.calls.DryRun = append(mock.calls.DryRun, callInfo)
	mock.lockDryRun.Unlock()
	if mock.DryRunFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.DryRunFunc()
}

// DryRunCalls gets all the calls that were made to DryRun.
// Check the length with:
//
//	len(mockedConfigurator.DryRunCalls())
func (mock *ConfiguratorMock) DryRunCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDryRun.RLock()
	calls = mock.calls.DryRun
	mock.lockDryRun.RUnlock()
	return calls
}

// Ensure, that ReverterMock does implement Reverter.
// If this is not the case, regenerate this file with moq.
var _ Reverter = &ReverterMock{}

// ReverterMock is a mock implementation of Reverter.
//
//	func TestSomethingThatUsesReverter(t *testing.T) {
//
//		// make and configure a mocked Reverter
//		mockedReverter := &ReverterMock{
//			RevertFunc: func() error {
//				panic("mock out the Revert method")
//			},
//		}
//
//		// use mockedReverter in code that requires Reverter
//		// and then make assertions.
//
//	}
type ReverterMock struct {
	// RevertFunc mocks the Revert method.
	RevertFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Revert holds details about calls to the Revert method.
		Revert []struct {
		}
	}
	lockRevert sync.RWMutex
}

// Revert calls RevertFunc.
func (mock *ReverterMock) Revert() error {
	callInfo := struct {
	}{}
	mock.lockRevert.Lock()
	mock.calls.Revert = append(mock.calls.Revert, callInfo)
	mock.lockRevert.Unlock()
	if mock.RevertFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RevertFunc()
}

// RevertCalls gets all the calls that were made to Revert.
// Check the length with:
//
//	len(mockedReverter.RevertCalls())
func (mock *ReverterMock) RevertCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRevert.RLock()
	calls = mock.calls.Revert
	mock.lockRevert.RUnlock()
	return calls
}
