/*
Copyright 2026 Rebellions Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package discover

import (
	"sync"
)

// Ensure, that DiscovererMock does implement Discoverer.
// If this is not the case, regenerate this file with moq.
var _ Discoverer = &DiscovererMock{}

// DiscovererMock is a mock implementation of Discoverer.
//
//	func TestSomethingThatUsesDiscoverer(t *testing.T) {
//
//		// make and configure a mocked Discoverer
//		mockedDiscoverer := &DiscovererMock{
//			DiscoverFunc: func() (*DiscoveryResult, error) {
//				panic("mock out the Discover method")
//			},
//		}
//
//		// use mockedDiscoverer in code that requires Discoverer
//		// and then make assertions.
//
//	}
type DiscovererMock struct {
	// DiscoverFunc mocks the Discover method.
	DiscoverFunc func() (*DiscoveryResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Discover holds details about calls to the Discover method.
		Discover []struct {
		}
	}
	lockDiscover sync.RWMutex
}

// Discover calls DiscoverFunc.
func (mock *DiscovererMock) Discover() (*DiscoveryResult, error) {
	callInfo := struct {
	}{}
	mock.lockDiscover.Lock()
	mock.calls.Discover = append(mock.calls.Discover, callInfo)
	mock.lockDiscover.Unlock()
	if mock.DiscoverFunc == nil {
		var (
			discoveryResultOut *DiscoveryResult
			errOut             error
		)
		return discoveryResultOut, errOut
	}
	return mock.DiscoverFunc()
}

// DiscoverCalls gets all the calls that were made to Discover.
// Check the length with:
//
//	len(mockedDiscoverer.DiscoverCalls())
func (mock *DiscovererMock) DiscoverCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDiscover.RLock()
	calls = mock.calls.Discover
	mock.lockDiscover.RUnlock()
	return calls
}

// Ensure, that LibraryDiscovererMock does implement LibraryDiscoverer.
// If this is not the case, regenerate this file with moq.
var _ LibraryDiscoverer = &LibraryDiscovererMock{}

// LibraryDiscovererMock is a mock implementation of LibraryDiscoverer.
//
//	func TestSomethingThatUsesLibraryDiscoverer(t *testing.T) {
//
//		// make and configure a mocked LibraryDiscoverer
//		mockedLibraryDiscoverer := &LibraryDiscovererMock{
//			DiscoverDependenciesFunc: func(libs []Library) ([]Library, error) {
//				panic("mock out the DiscoverDependencies method")
//			},
//			DiscoverPluginsFunc: func() ([]Library, error) {
//				panic("mock out the DiscoverPlugins method")
//			},
//			DiscoverRBLNFunc: func() ([]Library, error) {
//				panic("mock out the DiscoverRBLN method")
//			},
//		}
//
//		// use mockedLibraryDiscoverer in code that requires LibraryDiscoverer
//		// and then make assertions.
//
//	}
type LibraryDiscovererMock struct {
	// DiscoverDependenciesFunc mocks the DiscoverDependencies method.
	DiscoverDependenciesFunc func(libs []Library) ([]Library, error)

	// DiscoverPluginsFunc mocks the DiscoverPlugins method.
	DiscoverPluginsFunc func() ([]Library, error)

	// DiscoverRBLNFunc mocks the DiscoverRBLN method.
	DiscoverRBLNFunc func() ([]Library, error)

	// calls tracks calls to the methods.
	calls struct {
		// DiscoverDependencies holds details about calls to the DiscoverDependencies method.
		DiscoverDependencies []struct {
			// Libs is the libs argument value.
			Libs []Library
		}
		// DiscoverPlugins holds details about calls to the DiscoverPlugins method.
		DiscoverPlugins []struct {
		}
		// DiscoverRBLN holds details about calls to the DiscoverRBLN method.
		DiscoverRBLN []struct {
		}
	}
	lockDiscoverDependencies sync.RWMutex
	lockDiscoverPlugins      sync.RWMutex
	lockDiscoverRBLN         sync.RWMutex
}

// DiscoverDependencies calls DiscoverDependenciesFunc.
func (mock *LibraryDiscovererMock) DiscoverDependencies(libs []Library) ([]Library, error) {
	callInfo := struct {
		Libs []Library
	}{
		Libs: libs,
	}
	mock.lockDiscoverDependencies.Lock()
	mock.calls.DiscoverDependencies = append(mock.calls.DiscoverDependencies, callInfo)
	mock.lockDiscoverDependencies.Unlock()
	if mock.DiscoverDependenciesFunc == nil {
		var (
			librarysOut []Library
			errOut      error
		)
		return librarysOut, errOut
	}
	return mock.DiscoverDependenciesFunc(libs)
}

// DiscoverDependenciesCalls gets all the calls that were made to DiscoverDependencies.
// Check the length with:
//
//	len(mockedLibraryDiscoverer.DiscoverDependenciesCalls())
func (mock *LibraryDiscovererMock) DiscoverDependenciesCalls() []struct {
	Libs []Library
} {
	var calls []struct {
		Libs []Library
	}
	mock.lockDiscoverDependencies.RLock()
	calls = mock.calls.DiscoverDependencies
	mock.lockDiscoverDependencies.RUnlock()
	return calls
}

// DiscoverPlugins calls DiscoverPluginsFunc.
func (mock *LibraryDiscovererMock) DiscoverPlugins() ([]Library, error) {
	callInfo := struct {
	}{}
	mock.lockDiscoverPlugins.Lock()
	mock.calls.DiscoverPlugins = append(mock.calls.DiscoverPlugins, callInfo)
	mock.lockDiscoverPlugins.Unlock()
	if mock.DiscoverPluginsFunc == nil {
		var (
			librarysOut []Library
			errOut      error
		)
		return librarysOut, errOut
	}
	return mock.DiscoverPluginsFunc()
}

// DiscoverPluginsCalls gets all the calls that were made to DiscoverPlugins.
// Check the length with:
//
//	len(mockedLibraryDiscoverer.DiscoverPluginsCalls())
func (mock *LibraryDiscovererMock) DiscoverPluginsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDiscoverPlugins.RLock()
	calls = mock.calls.DiscoverPlugins
	mock.lockDiscoverPlugins.RUnlock()
	return calls
}

// DiscoverRBLN calls DiscoverRBLNFunc.
func (mock *LibraryDiscovererMock) DiscoverRBLN() ([]Library, error) {
	callInfo := struct {
	}{}
	mock.lockDiscoverRBLN.Lock()
	mock.calls.DiscoverRBLN = append(mock.calls.DiscoverRBLN, callInfo)
	mock.lockDiscoverRBLN.Unlock()
	if mock.DiscoverRBLNFunc == nil {
		var (
			librarysOut []Library
			errOut      error
		)
		return librarysOut, errOut
	}
	return mock.DiscoverRBLNFunc()
}

// DiscoverRBLNCalls gets all the calls that were made to DiscoverRBLN.
// Check the length with:
//
//	len(mockedLibraryDiscoverer.DiscoverRBLNCalls())
func (mock *LibraryDiscovererMock) DiscoverRBLNCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDiscoverRBLN.RLock()
	calls = mock.calls.DiscoverRBLN
	mock.lockDiscoverRBLN.RUnlock()
	return calls
}

// Ensure, that ToolDiscovererMock does implement ToolDiscoverer.
// If this is not the case, regenerate this file with moq.
var _ ToolDiscoverer = &ToolDiscovererMock{}

// ToolDiscovererMock is a mock implementation of ToolDiscoverer.
//
//	func TestSomethingThatUsesToolDiscoverer(t *testing.T) {
//
//		// make and configure a mocked ToolDiscoverer
//		mockedToolDiscoverer := &ToolDiscovererMock{
//			DiscoverFunc: func() ([]Tool, error) {
//				panic("mock out the Discover method")
//			},
//		}
//
//		// use mockedToolDiscoverer in code that requires ToolDiscoverer
//		// and then make assertions.
//
//	}
type ToolDiscovererMock struct {
	// DiscoverFunc mocks the Discover method.
	DiscoverFunc func() ([]Tool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Discover holds details about calls to the Discover method.
		Discover []struct {
		}
	}
	lockDiscover sync.RWMutex
}

// Discover calls DiscoverFunc.
func (mock *ToolDiscovererMock) Discover() ([]Tool, error) {
	callInfo := struct {
	}{}
	mock.lockDiscover.Lock()
	mock.calls.Discover = append(mock.calls.Discover, callInfo)
	mock.lockDiscover.Unlock()
	if mock.DiscoverFunc == nil {
		var (
			toolsOut []Tool
			errOut   error
		)
		return toolsOut, errOut
	}
	return mock.DiscoverFunc()
}

// DiscoverCalls gets all the calls that were made to Discover.
// Check the length with:
//
//	len(mockedToolDiscoverer.DiscoverCalls())
func (mock *ToolDiscovererMock) DiscoverCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDiscover.RLock()
	calls = mock.calls.Discover
	mock.lockDiscover.RUnlock()
	return calls
}
