/*
Copyright 2026 Rebellions Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package discover

import (
	"sync"
)

// Ensure, that LDCacheMock does implement LDCache.
// If this is not the case, regenerate this file with moq.
var _ LDCache = &LDCacheMock{}

// LDCacheMock is a mock implementation of LDCache.
//
//	func TestSomethingThatUsesLDCache(t *testing.T) {
//
//		// make and configure a mocked LDCache
//		mockedLDCache := &LDCacheMock{
//			ListFunc: func() ([]string, []string) {
//				panic("mock out the List method")
//			},
//			LookupFunc: func(pattern string) ([]string, error) {
//				panic("mock out the Lookup method")
//			},
//		}
//
//		// use mockedLDCache in code that requires LDCache
//		// and then make assertions.
//
//	}
type LDCacheMock struct {
	// ListFunc mocks the List method.
	ListFunc func() ([]string, []string)

	// LookupFunc mocks the Lookup method.
	LookupFunc func(pattern string) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
		}
		// Lookup holds details about calls to the Lookup method.
		Lookup []struct {
			// Pattern is the pattern argument value.
			Pattern string
		}
	}
	lockList   sync.RWMutex
	lockLookup sync.RWMutex
}

// List calls ListFunc.
func (mock *LDCacheMock) List() ([]string, []string) {
	callInfo := struct {
	}{}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			stringsOut1 []string
			stringsOut2 []string
		)
		return stringsOut1, stringsOut2
	}
	return mock.ListFunc()
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedLDCache.ListCalls())
func (mock *LDCacheMock) ListCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Lookup calls LookupFunc.
func (mock *LDCacheMock) Lookup(pattern string) ([]string, error) {
	callInfo := struct {
		Pattern string
	}{
		Pattern: pattern,
	}
	mock.lockLookup.Lock()
	mock.calls.Lookup = append(mock.calls.Lookup, callInfo)
	mock.lockLookup.Unlock()
	if mock.LookupFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.LookupFunc(pattern)
}

// LookupCalls gets all the calls that were made to Lookup.
// Check the length with:
//
//	len(mockedLDCache.LookupCalls())
func (mock *LDCacheMock) LookupCalls() []struct {
	Pattern string
} {
	var calls []struct {
		Pattern string
	}
	mock.lockLookup.RLock()
	calls = mock.calls.Lookup
	mock.lockLookup.RUnlock()
	return calls
}
