/*
Copyright 2026 Rebellions Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package discover

import (
	"sync"
)

// Ensure, that LDDRunnerMock does implement LDDRunner.
// If this is not the case, regenerate this file with moq.
var _ LDDRunner = &LDDRunnerMock{}

// LDDRunnerMock is a mock implementation of LDDRunner.
//
//	func TestSomethingThatUsesLDDRunner(t *testing.T) {
//
//		// make and configure a mocked LDDRunner
//		mockedLDDRunner := &LDDRunnerMock{
//			RunFunc: func(libraryPath string) ([]string, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedLDDRunner in code that requires LDDRunner
//		// and then make assertions.
//
//	}
type LDDRunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(libraryPath string) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// LibraryPath is the libraryPath argument value.
			LibraryPath string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *LDDRunnerMock) Run(libraryPath string) ([]string, error) {
	callInfo := struct {
		LibraryPath string
	}{
		LibraryPath: libraryPath,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	if mock.RunFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.RunFunc(libraryPath)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedLDDRunner.RunCalls())
func (mock *LDDRunnerMock) RunCalls() []struct {
	LibraryPath string
} {
	var calls []struct {
		LibraryPath string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
