#!/usr/bin/env bash
# sanitize-commit-message.sh — Strip internal-only references from a commit
# message before it is mirrored to the public repository.
#
# Reads one commit message on stdin, writes the cleaned message on stdout.
# Used as the `--msg-filter` of the history rewrite in release-mirror.sh and
# runnable on its own for inspection:
#
#   git log -1 --format=%B | ./hack/sanitize-commit-message.sh
#
# What gets removed (see hack/ci/test-sanitize-commit-message.sh for examples):
#   - internal tracker IDs (`[DOLIN-4371]`, `(DEVOPS-1352)`, bare `DOLIN-1219`
#     or `DOLIN-*` in prose, and `Closes: DEVOPS-1352`-style trailer lines)
#   - pull-request numbers GitHub appends on squash merge (`(#43)`) and bare
#     `PR #41` mentions — PRs live in the internal repo, so the numbers point
#     nowhere on the public mirror
#   - AI co-author trailers and generator footers
#
# The tracker keys are configurable through INTERNAL_TRACKER_KEYS
# (pipe-separated, default below) so a new internal project key can be added
# without touching the sed program.
#
# Requires GNU sed (word boundaries, case-insensitive delete) — the mirror job
# runs on Ubuntu, and this script is not part of the shipped toolkit.

set -euo pipefail

KEYS="${INTERNAL_TRACKER_KEYS:-DOLIN|DEVOPS|DOJIRA|SSWCI|SSW}"

sed -E \
    -e '/^[[:space:]]*[Cc]o-[Aa]uthored-[Bb]y:.*<noreply@anthropic\.com>/d' \
    -e '/^[[:space:]]*[Cc]o-[Aa]uthored-[Bb]y:[[:space:]]*Claude\b/d' \
    -e '/Generated (with|by) \[?Claude Code/d' \
    -e '/Generated by oh-my-devops:/d' \
    -e "/^[[:space:]]*-?[[:space:]]*(Closes?|Fixe?s?|Resolves?|Refs?|Related|Ticket|Linear|Jira)[[:space:]]*:?[[:space:]]+\[?(${KEYS})-[0-9]+/Id" \
    -e "s/[[:space:]]*[\\[(](${KEYS})-([0-9]+|\\*)[])]//g" \
    -e 's/[[:space:]]*\(#[0-9]+\)//g' \
    -e 's/^PR #[0-9]+\b/An earlier PR/' \
    -e 's/\bPR #[0-9]+\b/an earlier PR/g' \
    -e "s/\\b(${KEYS})-([0-9]+\\b|\\*)/[internal ticket]/g" \
    | git stripspace
