/*
Copyright 2026 Rebellions Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cdi

import (
	"sync"

	"github.com/RBLN-SW/rbln-container-toolkit/internal/discover"
	"tags.cncf.io/container-device-interface/specs-go"
)

// Ensure, that GeneratorMock does implement Generator.
// If this is not the case, regenerate this file with moq.
var _ Generator = &GeneratorMock{}

// GeneratorMock is a mock implementation of Generator.
//
//	func TestSomethingThatUsesGenerator(t *testing.T) {
//
//		// make and configure a mocked Generator
//		mockedGenerator := &GeneratorMock{
//			GenerateFunc: func(result *discover.DiscoveryResult) (*specs.Spec, error) {
//				panic("mock out the Generate method")
//			},
//		}
//
//		// use mockedGenerator in code that requires Generator
//		// and then make assertions.
//
//	}
type GeneratorMock struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(result *discover.DiscoveryResult) (*specs.Spec, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// Result is the result argument value.
			Result *discover.DiscoveryResult
		}
	}
	lockGenerate sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *GeneratorMock) Generate(result *discover.DiscoveryResult) (*specs.Spec, error) {
	callInfo := struct {
		Result *discover.DiscoveryResult
	}{
		Result: result,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	if mock.GenerateFunc == nil {
		var (
			specOut *specs.Spec
			errOut  error
		)
		return specOut, errOut
	}
	return mock.GenerateFunc(result)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedGenerator.GenerateCalls())
func (mock *GeneratorMock) GenerateCalls() []struct {
	Result *discover.DiscoveryResult
} {
	var calls []struct {
		Result *discover.DiscoveryResult
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}
