/*
Copyright 2026 Rebellions Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cdi

import (
	"sync"

	"tags.cncf.io/container-device-interface/specs-go"
)

// Ensure, that ValidatorMock does implement Validator.
// If this is not the case, regenerate this file with moq.
var _ Validator = &ValidatorMock{}

// ValidatorMock is a mock implementation of Validator.
//
//	func TestSomethingThatUsesValidator(t *testing.T) {
//
//		// make and configure a mocked Validator
//		mockedValidator := &ValidatorMock{
//			ValidateFunc: func(spec *specs.Spec) error {
//				panic("mock out the Validate method")
//			},
//			ValidateFileFunc: func(path string) error {
//				panic("mock out the ValidateFile method")
//			},
//		}
//
//		// use mockedValidator in code that requires Validator
//		// and then make assertions.
//
//	}
type ValidatorMock struct {
	// ValidateFunc mocks the Validate method.
	ValidateFunc func(spec *specs.Spec) error

	// ValidateFileFunc mocks the ValidateFile method.
	ValidateFileFunc func(path string) error

	// calls tracks calls to the methods.
	calls struct {
		// Validate holds details about calls to the Validate method.
		Validate []struct {
			// Spec is the spec argument value.
			Spec *specs.Spec
		}
		// ValidateFile holds details about calls to the ValidateFile method.
		ValidateFile []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockValidate     sync.RWMutex
	lockValidateFile sync.RWMutex
}

// Validate calls ValidateFunc.
func (mock *ValidatorMock) Validate(spec *specs.Spec) error {
	callInfo := struct {
		Spec *specs.Spec
	}{
		Spec: spec,
	}
	mock.lockValidate.Lock()
	mock.calls.Validate = append(mock.calls.Validate, callInfo)
	mock.lockValidate.Unlock()
	if mock.ValidateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ValidateFunc(spec)
}

// ValidateCalls gets all the calls that were made to Validate.
// Check the length with:
//
//	len(mockedValidator.ValidateCalls())
func (mock *ValidatorMock) ValidateCalls() []struct {
	Spec *specs.Spec
} {
	var calls []struct {
		Spec *specs.Spec
	}
	mock.lockValidate.RLock()
	calls = mock.calls.Validate
	mock.lockValidate.RUnlock()
	return calls
}

// ValidateFile calls ValidateFileFunc.
func (mock *ValidatorMock) ValidateFile(path string) error {
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockValidateFile.Lock()
	mock.calls.ValidateFile = append(mock.calls.ValidateFile, callInfo)
	mock.lockValidateFile.Unlock()
	if mock.ValidateFileFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ValidateFileFunc(path)
}

// ValidateFileCalls gets all the calls that were made to ValidateFile.
// Check the length with:
//
//	len(mockedValidator.ValidateFileCalls())
func (mock *ValidatorMock) ValidateFileCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockValidateFile.RLock()
	calls = mock.calls.ValidateFile
	mock.lockValidateFile.RUnlock()
	return calls
}
