/*
Copyright 2026 Rebellions Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cdi

import (
	"io"
	"sync"

	"tags.cncf.io/container-device-interface/specs-go"
)

// Ensure, that WriterMock does implement Writer.
// If this is not the case, regenerate this file with moq.
var _ Writer = &WriterMock{}

// WriterMock is a mock implementation of Writer.
//
//	func TestSomethingThatUsesWriter(t *testing.T) {
//
//		// make and configure a mocked Writer
//		mockedWriter := &WriterMock{
//			WriteFunc: func(spec *specs.Spec, path string, format string) error {
//				panic("mock out the Write method")
//			},
//			WriteToWriterFunc: func(spec *specs.Spec, w io.Writer, format string) error {
//				panic("mock out the WriteToWriter method")
//			},
//		}
//
//		// use mockedWriter in code that requires Writer
//		// and then make assertions.
//
//	}
type WriterMock struct {
	// WriteFunc mocks the Write method.
	WriteFunc func(spec *specs.Spec, path string, format string) error

	// WriteToWriterFunc mocks the WriteToWriter method.
	WriteToWriterFunc func(spec *specs.Spec, w io.Writer, format string) error

	// calls tracks calls to the methods.
	calls struct {
		// Write holds details about calls to the Write method.
		Write []struct {
			// Spec is the spec argument value.
			Spec *specs.Spec
			// Path is the path argument value.
			Path string
			// Format is the format argument value.
			Format string
		}
		// WriteToWriter holds details about calls to the WriteToWriter method.
		WriteToWriter []struct {
			// Spec is the spec argument value.
			Spec *specs.Spec
			// W is the w argument value.
			W io.Writer
			// Format is the format argument value.
			Format string
		}
	}
	lockWrite         sync.RWMutex
	lockWriteToWriter sync.RWMutex
}

// Write calls WriteFunc.
func (mock *WriterMock) Write(spec *specs.Spec, path string, format string) error {
	callInfo := struct {
		Spec   *specs.Spec
		Path   string
		Format string
	}{
		Spec:   spec,
		Path:   path,
		Format: format,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	if mock.WriteFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.WriteFunc(spec, path, format)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedWriter.WriteCalls())
func (mock *WriterMock) WriteCalls() []struct {
	Spec   *specs.Spec
	Path   string
	Format string
} {
	var calls []struct {
		Spec   *specs.Spec
		Path   string
		Format string
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}

// WriteToWriter calls WriteToWriterFunc.
func (mock *WriterMock) WriteToWriter(spec *specs.Spec, w io.Writer, format string) error {
	callInfo := struct {
		Spec   *specs.Spec
		W      io.Writer
		Format string
	}{
		Spec:   spec,
		W:      w,
		Format: format,
	}
	mock.lockWriteToWriter.Lock()
	mock.calls.WriteToWriter = append(mock.calls.WriteToWriter, callInfo)
	mock.lockWriteToWriter.Unlock()
	if mock.WriteToWriterFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.WriteToWriterFunc(spec, w, format)
}

// WriteToWriterCalls gets all the calls that were made to WriteToWriter.
// Check the length with:
//
//	len(mockedWriter.WriteToWriterCalls())
func (mock *WriterMock) WriteToWriterCalls() []struct {
	Spec   *specs.Spec
	W      io.Writer
	Format string
} {
	var calls []struct {
		Spec   *specs.Spec
		W      io.Writer
		Format string
	}
	mock.lockWriteToWriter.RLock()
	calls = mock.calls.WriteToWriter
	mock.lockWriteToWriter.RUnlock()
	return calls
}
