#!/usr/bin/env bash
# test-sanitize-commit-message.sh — Table-driven checks for
# hack/sanitize-commit-message.sh. Each case feeds a message through the
# filter and compares the result byte-for-byte with the expected output.
#
# Usage: ./hack/ci/test-sanitize-commit-message.sh

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SANITIZE="${HERE}/../sanitize-commit-message.sh"

failures=0

# check <name> <input> <expected>
check() {
    local name="$1" input="$2" expected="$3" got
    got="$(printf '%s' "${input}" | "${SANITIZE}")"
    if [[ "${got}" == "${expected}" ]]; then
        echo "ok   ${name}"
    else
        echo "FAIL ${name}"
        echo "  --- expected"
        printf '%s\n' "${expected}" | sed 's/^/  | /'
        echo "  --- got"
        printf '%s\n' "${got}" | sed 's/^/  | /'
        failures=$((failures + 1))
    fi
}

check "squash-merge subject: ticket + PR number" \
'fix(cdi): expose RSD group device as /dev/rsd0 [DOLIN-4371] (#43)

Body text stays.' \
'fix(cdi): expose RSD group device as /dev/rsd0

Body text stays.'

check "PR number only" \
'docs(changelog): add v0.2.4 section (#42)' \
'docs(changelog): add v0.2.4 section'

check "parenthesised ticket in squash body bullets" \
'feat(cdi): RDS char device class (#34)

* feat(config): add RDS char device CDI class config (DOLIN-2324)
* feat(cdi): classify /dev/rblnfs and generate the RDS CDI spec (DOLIN-2324)' \
'feat(cdi): RDS char device class

* feat(config): add RDS char device CDI class config
* feat(cdi): classify /dev/rblnfs and generate the RDS CDI spec'

check "AI co-author trailers dropped, both capitalisations" \
'fix(daemon): skip runtime restart

Explanation.

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>
Co-authored-by: Claude Fable 5 <noreply@anthropic.com>
Co-authored-by: Claude Opus 4.6 (1M context) <noreply@anthropic.com>' \
'fix(daemon): skip runtime restart

Explanation.'

check "human co-author trailer kept" \
'feat: pair-programmed change

Co-authored-by: Jane Doe <jane@example.com>' \
'feat: pair-programmed change

Co-authored-by: Jane Doe <jane@example.com>'

check "generator footers dropped" \
'fix(runtime): judge CRI-O readiness

Details.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

_Generated by oh-my-devops:pr-create v2.14.0_' \
'fix(runtime): judge CRI-O readiness

Details.'

check "ticket trailer lines dropped" \
'feat(ci): add workflow

Closes: DEVOPS-1352
Refs: DEVOPS-1363
Resolves: DEVOPS-1364
closes DOLIN-4371
- closes DOLIN-4371
Linear: [DOLIN-3293](https://linear.app/rbln-ssw/issue/DOLIN-3293/slug)' \
'feat(ci): add workflow'

check "bare ticket ids in prose become a placeholder" \
'fix: tighten parser

Edge cases wrong across the DOLIN-2743 review rounds are fixed. The
smoke-test CI tracked in DOLIN-1985.
DOLIN-1219 renamed the legacy entry.' \
'fix: tighten parser

Edge cases wrong across the [internal ticket] review rounds are fixed. The
smoke-test CI tracked in [internal ticket].
[internal ticket] renamed the legacy entry.'

check "glob-style tracker reference" \
'chore: drop internal issue identifiers from code comments

The repository is open-sourced; remove internal tracker IDs (DOLIN-*) from
comments. Bare DOLIN-* mentions go too.' \
'chore: drop internal issue identifiers from code comments

The repository is open-sourced; remove internal tracker IDs from
comments. Bare [internal ticket] mentions go too.'

check "bare PR mentions reworded" \
'fix(discover): follow-up

PR #41 keyed the watcher on build-id.
Address PR #34 review (ssw-buildkite[bot]):' \
'fix(discover): follow-up

An earlier PR keyed the watcher on build-id.
Address an earlier PR review (ssw-buildkite[bot]):'

check "unrelated hyphenated tokens untouched" \
'feat: use SHA-256 and AVX-512 on RHEL-8

Also mention a hex #deadbeef and C++17.' \
'feat: use SHA-256 and AVX-512 on RHEL-8

Also mention a hex #deadbeef and C++17.'

# INTERNAL_TRACKER_KEYS overrides the default key list.
got="$(printf 'fix: thing [ACME-12] (#7)\n\nRefs: ACME-12\n' | INTERNAL_TRACKER_KEYS='ACME' "${SANITIZE}")"
if [[ "${got}" == 'fix: thing' ]]; then
    echo "ok   custom keys applied"
else
    echo "FAIL custom keys applied: got '${got}'"
    failures=$((failures + 1))
fi

check "clean message passes through unchanged" \
'docs(release): use no-dot rc convention in tag examples (rc.N -> rcN)

Keep everything.' \
'docs(release): use no-dot rc convention in tag examples (rc.N -> rcN)

Keep everything.'

check "trailing blank lines left by deletions are collapsed" \
'feat: thing

Body.


Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>

' \
'feat: thing

Body.'

if (( failures > 0 )); then
    echo "${failures} case(s) failed"
    exit 1
fi
echo "all cases passed"
