/*
Copyright 2026 Rebellions Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package restart

import (
	"sync"
)

// Ensure, that RestarterMock does implement Restarter.
// If this is not the case, regenerate this file with moq.
var _ Restarter = &RestarterMock{}

// RestarterMock is a mock implementation of Restarter.
//
//	func TestSomethingThatUsesRestarter(t *testing.T) {
//
//		// make and configure a mocked Restarter
//		mockedRestarter := &RestarterMock{
//			DryRunFunc: func(runtime string) string {
//				panic("mock out the DryRun method")
//			},
//			RestartFunc: func(runtime string) error {
//				panic("mock out the Restart method")
//			},
//		}
//
//		// use mockedRestarter in code that requires Restarter
//		// and then make assertions.
//
//	}
type RestarterMock struct {
	// DryRunFunc mocks the DryRun method.
	DryRunFunc func(runtime string) string

	// RestartFunc mocks the Restart method.
	RestartFunc func(runtime string) error

	// calls tracks calls to the methods.
	calls struct {
		// DryRun holds details about calls to the DryRun method.
		DryRun []struct {
			// Runtime is the runtime argument value.
			Runtime string
		}
		// Restart holds details about calls to the Restart method.
		Restart []struct {
			// Runtime is the runtime argument value.
			Runtime string
		}
	}
	lockDryRun  sync.RWMutex
	lockRestart sync.RWMutex
}

// DryRun calls DryRunFunc.
func (mock *RestarterMock) DryRun(runtime string) string {
	callInfo := struct {
		Runtime string
	}{
		Runtime: runtime,
	}
	mock.lockDryRun.Lock()
	mock.calls.DryRun = append(mock.calls.DryRun, callInfo)
	mock.lockDryRun.Unlock()
	if mock.DryRunFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.DryRunFunc(runtime)
}

// DryRunCalls gets all the calls that were made to DryRun.
// Check the length with:
//
//	len(mockedRestarter.DryRunCalls())
func (mock *RestarterMock) DryRunCalls() []struct {
	Runtime string
} {
	var calls []struct {
		Runtime string
	}
	mock.lockDryRun.RLock()
	calls = mock.calls.DryRun
	mock.lockDryRun.RUnlock()
	return calls
}

// Restart calls RestartFunc.
func (mock *RestarterMock) Restart(runtime string) error {
	callInfo := struct {
		Runtime string
	}{
		Runtime: runtime,
	}
	mock.lockRestart.Lock()
	mock.calls.Restart = append(mock.calls.Restart, callInfo)
	mock.lockRestart.Unlock()
	if mock.RestartFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RestartFunc(runtime)
}

// RestartCalls gets all the calls that were made to Restart.
// Check the length with:
//
//	len(mockedRestarter.RestartCalls())
func (mock *RestarterMock) RestartCalls() []struct {
	Runtime string
} {
	var calls []struct {
		Runtime string
	}
	mock.lockRestart.RLock()
	calls = mock.calls.Restart
	mock.lockRestart.RUnlock()
	return calls
}
